# -*- coding: utf-8 -*-
"""Pneumonia_DL_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfgA9h26fKY3ic1vG7CiSI5BTq5X_5o2

# Deep Learning CEP Project (BSE-634)
## Pneumonia Detection from Chest X-Ray Images
### Design and Optimization of Deep Learning Models on a Custom Image Dataset


**Dataset:** [Chest X-Ray Images (Pneumonia)](https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia) — Kaggle, by Paul Mooney. Binary classification: **NORMAL** vs **PNEUMONIA**.

**Architectures compared (Phase 2 & Phase 4):**
1. **Custom CNN** built from scratch
2. **ResNet50** (transfer learning, ImageNet weights)
3. **CNN + Transformer hybrid** (CNN stem → Transformer encoder blocks)

---
# PHASE 1 — Dataset Selection & Preprocessing

Steps covered:
1. Download dataset from Kaggle
2. Explore folder structure & class distribution
3. Check for corrupt/missing images
4. Re-split into **70% train / 20% validation / 10% test** (stratified)
5. Resize, normalize, and (for training) augment images
"""

# 1.1  Install & import libraries
!pip install -q kagglehub

import os, shutil, random, time, json, math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, optimizers, callbacks, regularizers

from sklearn.model_selection import train_test_split
from sklearn.metrics import (confusion_matrix, classification_report,
                              roc_curve, auc, precision_recall_fscore_support,
                              accuracy_score)
from sklearn.utils.class_weight import compute_class_weight

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

# 1.2  Download dataset from Kaggle (no API key needed via kagglehub)
import kagglehub

dataset_path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")
print("Dataset downloaded to:", dataset_path)

# Show top-level structure
for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    if level < 3:
        print('  ' * level + os.path.basename(root) + '/')

# 1.3  Build a single unified list of (filepath, label) from train/val/test folders
# The original Kaggle split has a very small 'val' folder (16 images), which violates
# good practice for stratified evaluation, so we pool everything and re-split ourselves
# (Phase 1 requirement: 70/20/10 train-val-test split).

base = Path(dataset_path) / "chest_xray"
classes = ["NORMAL", "PNEUMONIA"]
records = []
for split in ["train", "val", "test"]:
    for cls in classes:
        folder = base / split / cls
        if not folder.exists():
            continue
        for fp in folder.glob("*"):
            if fp.suffix.lower() in [".jpeg", ".jpg", ".png"]:
                records.append({"filepath": str(fp), "label": cls})

df = pd.DataFrame(records)
print("Total images found:", len(df))
print(df["label"].value_counts())

# 1.4  Class distribution plot (highlights the class-imbalance problem -> Phase 4)
plt.figure(figsize=(5,4))
sns.countplot(x="label", data=df, order=classes)
plt.title("Class Distribution (full pooled dataset)")
plt.xlabel("Class")
plt.ylabel("Number of images")
plt.show()

imbalance_ratio = df["label"].value_counts()["PNEUMONIA"] / df["label"].value_counts()["NORMAL"]
print(f"Imbalance ratio (PNEUMONIA / NORMAL): {imbalance_ratio:.2f} : 1")

# 1.5  Visualize sample images from each class
fig, axes = plt.subplots(2, 4, figsize=(14, 6))
for row, cls in enumerate(classes):
    sample_paths = df[df.label == cls].sample(4, random_state=SEED)["filepath"].tolist()
    for col, p in enumerate(sample_paths):
        img = keras.utils.load_img(p, color_mode="grayscale")
        axes[row, col].imshow(img, cmap="gray")
        axes[row, col].set_title(cls)
        axes[row, col].axis("off")
plt.tight_layout()
plt.show()

# 1.6  Check for corrupt / unreadable images and remove them (Phase 1: handle missing/bad data)
def is_valid_image(path):
    try:
        img = tf.io.read_file(path)
        tf.image.decode_jpeg(img, channels=3)
        return True
    except Exception:
        return False

# Sampling-based check for speed; on full run you may check all files
bad_files = []
for p in df["filepath"]:
    if not is_valid_image(p):
        bad_files.append(p)

print(f"Corrupt/unreadable images found: {len(bad_files)}")
df = df[~df["filepath"].isin(bad_files)].reset_index(drop=True)
print("Remaining images:", len(df))

# 1.7  Stratified 70 / 20 / 10 train-validation-test split
train_df, temp_df = train_test_split(
    df, test_size=0.30, stratify=df["label"], random_state=SEED
)
val_df, test_df = train_test_split(
    temp_df, test_size=1/3, stratify=temp_df["label"], random_state=SEED
)  # 1/3 of 30% = 10% of total

print("Train:", train_df.shape, "\nVal:  ", val_df.shape, "\nTest: ", test_df.shape)
print("\nTrain class balance:\n", train_df.label.value_counts(normalize=True))
print("\nVal class balance:\n", val_df.label.value_counts(normalize=True))
print("\nTest class balance:\n", test_df.label.value_counts(normalize=True))

"""### 1.8 Preprocessing pipeline

- **Resize** every image to `224 x 224` (standard input size compatible with ResNet50 and giving enough spatial resolution for the Transformer patch embedding).
- Convert grayscale X-rays to **3 channels** (required by ImageNet-pretrained ResNet50).
- **Normalize** pixel values to `[0, 1]`.
- **Augmentation** (training set only): random horizontal flip, small rotation, zoom, and brightness/contrast jitter — this directly targets **overfitting** (Phase 4) given the relatively small dataset and class imbalance.

"""

IMG_SIZE = 224
BATCH_SIZE = 32
LABEL_MAP = {"NORMAL": 0, "PNEUMONIA": 1}

def load_and_preprocess(filepath, label, augment=False):
    img = tf.io.read_file(filepath)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img = tf.cast(img, tf.float32) / 255.0
    if augment:
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_brightness(img, max_delta=0.1)
        img = tf.image.random_contrast(img, lower=0.9, upper=1.1)
        # small random rotation via random crop/zoom
        img = tf.image.resize_with_crop_or_pad(img, IMG_SIZE + 20, IMG_SIZE + 20)
        img = tf.image.random_crop(img, [IMG_SIZE, IMG_SIZE, 3])
    return img, label

def make_dataset(dataframe, augment=False, shuffle=False, batch_size=BATCH_SIZE):
    filepaths = dataframe["filepath"].values
    labels = dataframe["label"].map(LABEL_MAP).values.astype("int32")
    ds = tf.data.Dataset.from_tensor_slices((filepaths, labels))
    if shuffle:
        ds = ds.shuffle(buffer_size=len(filepaths), seed=SEED)
    ds = ds.map(lambda x, y: load_and_preprocess(x, y, augment=augment),
                num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

train_ds = make_dataset(train_df, augment=True, shuffle=True)
val_ds   = make_dataset(val_df, augment=False, shuffle=False)
test_ds  = make_dataset(test_df, augment=False, shuffle=False)

# sanity check
for imgs, lbls in train_ds.take(1):
    print("Batch image shape:", imgs.shape, "| Batch label shape:", lbls.shape)
    print("Pixel value range:", float(tf.reduce_min(imgs)), "-", float(tf.reduce_max(imgs)))

# 1.9  Class weights (to handle the class imbalance found in step 1.4)
y_train = train_df["label"].map(LABEL_MAP).values
class_weights_array = compute_class_weight(class_weight="balanced",
                                             classes=np.unique(y_train),
                                             y=y_train)
class_weights = {i: w for i, w in enumerate(class_weights_array)}
print("Class weights:", class_weights)

"""---
# PHASE 2 — Model Design and Implementation

We design and implement **three** architectures for the same binary classification task (Normal vs Pneumonia), so that Phase 3/4 can perform a fair analytical comparison.

| Model | Type | Pretrained? | Key idea |
|---|---|---|---|
| **Model A** | Custom CNN | No (from scratch) | Baseline convolutional feature extractor designed specifically for this dataset |
| **Model B** | ResNet50 | Yes (ImageNet) | Transfer learning — deep residual features, fine-tuned head |
| **Model C** | CNN + Transformer (hybrid) | No (from scratch) | CNN stem extracts local features; Transformer encoder models global/long-range dependencies between feature-map patches |

## Model A — Custom CNN (from scratch)

**Architecture justification:**
- 4 convolutional blocks (`Conv2D -> BatchNorm -> ReLU -> MaxPool`) with increasing filter counts (32 -> 64 -> 128 -> 256). Increasing depth lets the network learn from low-level edges/textures to high-level lesion/opacity patterns typical of pneumonia consolidation.
- **BatchNorm** after every conv layer stabilizes training and helps mitigate **vanishing/exploding gradients** (Phase 4 requirement).
- **ReLU** activations avoid vanishing gradients common with sigmoid/tanh in deep stacks.
- **GlobalAveragePooling2D** instead of Flatten + huge Dense layer — drastically reduces parameter count and overfitting risk.
- **Dropout (0.5)** before the final classifier — addresses overfitting (Phase 4).
- Output: single sigmoid neuron for binary classification (Normal=0, Pneumonia=1).
"""

def build_custom_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 3)):
    inputs = layers.Input(shape=input_shape)

    x = layers.Conv2D(32, 3, padding="same", activation=None)(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(64, 3, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(128, 3, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(256, 3, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D()(x)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(128, activation="relu",
                      kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inputs, outputs, name="custom_cnn")
    return model

custom_cnn = build_custom_cnn()
custom_cnn.summary()

"""## Model B — ResNet50 (Transfer Learning)

**Architecture justification:**
- Backbone: `ResNet50` pretrained on ImageNet. The residual ("skip") connections allow training of very deep networks without **vanishing gradients** — directly relevant to Phase 4's "vanishing gradient" mitigation discussion.
- The convolutional base is **frozen initially** (feature extraction mode) so we reuse low-level visual features (edges, blobs, textures) learned from millions of natural images — useful even for X-rays at the early-layer level.
- A new classification head is added: `GlobalAveragePooling2D -> Dropout -> Dense(128, relu) -> Dropout -> Dense(1, sigmoid)`.
- Optionally, the **top layers can be unfrozen and fine-tuned** at a low learning rate after initial training — a standard transfer-learning practice that improves domain adaptation to medical images.

"""

def build_resnet50(input_shape=(IMG_SIZE, IMG_SIZE, 3), fine_tune_at=None):
    base_model = keras.applications.ResNet50(
        include_top=False, weights="imagenet", input_shape=input_shape
    )
    base_model.trainable = False  # freeze for initial training (feature extraction)

    if fine_tune_at is not None:
        base_model.trainable = True
        for layer in base_model.layers[:fine_tune_at]:
            layer.trainable = False

    inputs = layers.Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(128, activation="relu",
                      kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inputs, outputs, name="resnet50_transfer")
    return model, base_model

resnet_model, resnet_base = build_resnet50()
resnet_model.summary()

"""## Model C — CNN + Transformer Hybrid

**Architecture justification:**
- A small **CNN stem** (3 conv blocks with stride/pooling) reduces the 224x224 image to a compact feature map (e.g. 28x28xC), extracting local textures cheaply before the more expensive Transformer stage.
- The feature map is reshaped into a **sequence of patch embeddings** (each spatial location = one "token", projected to `embed_dim`).
- A **learnable positional embedding** is added (Transformers have no inherent notion of spatial order).
- **Transformer encoder blocks** (Multi-Head Self-Attention + residual connections + LayerNorm + feed-forward MLP) let the model learn **global relationships** between distant regions of the lung (e.g. bilateral infiltrates), which pure CNNs with small receptive fields can miss.
- **GlobalAveragePooling1D** over the token sequence -> Dense classifier head.
- Residual connections + LayerNorm in the Transformer blocks help control **vanishing gradients** in this deeper, mixed architecture (Phase 4).

"""

class TransformerEncoderBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, dropout=0.1, **kwargs):
        super().__init__(**kwargs)
        self.att = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim // num_heads)
        self.ffn = models.Sequential([
            layers.Dense(ff_dim, activation="relu"),
            layers.Dense(embed_dim),
        ])
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(dropout)
        self.dropout2 = layers.Dropout(dropout)

    def call(self, inputs, training=False):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)          # residual connection 1
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)             # residual connection 2


def build_cnn_transformer(input_shape=(IMG_SIZE, IMG_SIZE, 3),
                           embed_dim=128, num_heads=4, ff_dim=256,
                           num_transformer_blocks=2):
    inputs = layers.Input(shape=input_shape)

    # ---- CNN stem (local feature extraction) ----
    x = layers.Conv2D(32, 3, strides=2, padding="same", activation="relu")(inputs)  # 112x112
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(64, 3, strides=2, padding="same", activation="relu")(x)        # 56x56
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(embed_dim, 3, strides=2, padding="same", activation="relu")(x) # 28x28xembed_dim
    x = layers.BatchNormalization()(x)

    # ---- Reshape feature map into a sequence of patch tokens ----
    h, w, c = x.shape[1], x.shape[2], x.shape[3]
    num_patches = h * w
    x = layers.Reshape((num_patches, c))(x)

    # ---- Learnable positional embedding ----
    positions = tf.range(start=0, limit=num_patches, delta=1)
    pos_embedding = layers.Embedding(input_dim=num_patches, output_dim=embed_dim)(positions)
    x = x + pos_embedding

    # ---- Transformer encoder blocks ----
    for _ in range(num_transformer_blocks):
        x = TransformerEncoderBlock(embed_dim, num_heads, ff_dim, dropout=0.1)(x)

    # ---- Classification head ----
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dropout(0.4)(x)
    x = layers.Dense(128, activation="relu",
                      kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inputs, outputs, name="cnn_transformer_hybrid")
    return model

cnn_transformer = build_cnn_transformer()
cnn_transformer.summary()

"""---
# PHASE 3 — Model Training, Tuning, and Evaluation

This phase covers:
1. Common callbacks (early stopping, LR scheduling, checkpointing)
2. **Optimizer comparison** (Adam vs SGD vs RMSprop) on a quick run
3. **Hyperparameter tuning** (batch size, learning rate, dropout)
4. Full training of Models A, B, C
5. Evaluation: Accuracy, Precision, Recall, F1, AUC, confusion matrix, learning curves

"""

# 3.1  Common callbacks
def get_callbacks(model_name):
    return [
        callbacks.EarlyStopping(monitor="val_loss", patience=4, restore_best_weights=True),
        callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-6),
        callbacks.ModelCheckpoint(f"{model_name}_best.keras", monitor="val_loss", save_best_only=True),
    ]

METRICS = [
    keras.metrics.BinaryAccuracy(name="accuracy"),
    keras.metrics.Precision(name="precision"),
    keras.metrics.Recall(name="recall"),
    keras.metrics.AUC(name="auc"),
]

"""## 3.2 Optimizer Comparison (Adam vs SGD vs RMSprop)

To satisfy Phase 3.2(a) — "Experiment with optimizers" — we run a **short** training run (a few epochs) of the **custom CNN** with three optimizers and compare validation accuracy/loss curves. This is a *diagnostic* experiment; the full training runs in Section 3.4 use the best-performing optimizer (typically Adam).

"""

# 3.2  Optimizer comparison experiment (short runs, e.g. 5 epochs each)
OPT_EPOCHS = 5

optimizer_configs = {
    "Adam":    optimizers.Adam(learning_rate=1e-3),
    "SGD":     optimizers.SGD(learning_rate=1e-3, momentum=0.9),
    "RMSprop": optimizers.RMSprop(learning_rate=1e-3),
}

optimizer_histories = {}
for name, opt in optimizer_configs.items():
    print(f"\n=== Training with {name} ===")
    model_tmp = build_custom_cnn()
    model_tmp.compile(optimizer=opt, loss="binary_crossentropy", metrics=METRICS)
    hist = model_tmp.fit(train_ds, validation_data=val_ds, epochs=OPT_EPOCHS,
                          class_weight=class_weights, verbose=1)
    optimizer_histories[name] = hist.history

# 3.2b  Plot optimizer comparison
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for name, hist in optimizer_histories.items():
    axes[0].plot(hist["val_loss"], label=name)
    axes[1].plot(hist["val_accuracy"], label=name)
axes[0].set_title("Validation Loss"); axes[0].set_xlabel("Epoch"); axes[0].legend()
axes[1].set_title("Validation Accuracy"); axes[1].set_xlabel("Epoch"); axes[1].legend()
plt.tight_layout()
plt.show()

"""## 3.3 Hyperparameter Tuning (Batch Size, Learning Rate, Dropout)

A small grid search over `batch_size`, `learning_rate`, and `dropout` for the custom CNN, trained for a few epochs each (Phase 3.2(b)).

"""

# 3.3  Small hyperparameter grid search (short runs) — now includes optimizer choice
TUNE_EPOCHS = 3
param_grid = [
    {"batch_size": 32, "lr": 1e-4, "dropout": 0.5, "optimizer": "adam"},
    {"batch_size": 32, "lr": 1e-3, "dropout": 0.5, "optimizer": "sgd"},
    {"batch_size": 64, "lr": 1e-4, "dropout": 0.3, "optimizer": "adam"},
    {"batch_size": 32, "lr": 1e-4, "dropout": 0.3, "optimizer": "sgd"},
]

def build_custom_cnn_param(dropout1=0.5, dropout2=0.3, input_shape=(IMG_SIZE, IMG_SIZE, 3)):
    inputs = layers.Input(shape=input_shape)
    x = inputs
    for filters in [32, 64, 128, 256]:
        x = layers.Conv2D(filters, 3, padding="same")(x)
        x = layers.BatchNormalization()(x)
        x = layers.Activation("relu")(x)
        x = layers.MaxPooling2D()(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(dropout1)(x)
    x = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(dropout2)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)
    return models.Model(inputs, outputs)

def get_optimizer(name, lr):
    if name == "adam":
        return optimizers.Adam(learning_rate=lr, clipnorm=1.0)
    elif name == "sgd":
        return optimizers.SGD(learning_rate=lr, momentum=0.9)
    elif name == "rmsprop":
        return optimizers.RMSprop(learning_rate=lr, clipnorm=1.0)

tuning_results = []
for cfg in param_grid:
    print(f"\n=== Config: {cfg} ===")
    tr_ds = make_dataset(train_df, augment=True, shuffle=True, batch_size=cfg["batch_size"])
    va_ds = make_dataset(val_df, augment=False, shuffle=False, batch_size=cfg["batch_size"])

    m = build_custom_cnn_param(dropout1=cfg["dropout"])
    m.compile(optimizer=get_optimizer(cfg["optimizer"], cfg["lr"]),
              loss="binary_crossentropy", metrics=METRICS)
    hist = m.fit(tr_ds, validation_data=va_ds, epochs=TUNE_EPOCHS,
                  class_weight=class_weights, verbose=0)

    tuning_results.append({
        **cfg,
        "val_accuracy": hist.history["val_accuracy"][-1],
        "val_loss": hist.history["val_loss"][-1],
    })

tuning_df = pd.DataFrame(tuning_results)
tuning_df

"""## 3.4 Full Training of Models A, B, and C

Choose the **best optimizer / hyperparameters** found above

"""

EPOCHS = 30  # bumped up since SGD at a low LR converges more slowly; early stopping will still cut it short if needed

# ---- Model A: Custom CNN ----
custom_cnn = build_custom_cnn_param(dropout1=0.3, dropout2=0.3)  # dropout=0.3 matched winning tuning config
custom_cnn.compile(optimizer=optimizers.SGD(learning_rate=1e-4, momentum=0.9, clipnorm=1.0),
                    loss="binary_crossentropy", metrics=METRICS)
history_cnn = custom_cnn.fit(
    train_ds, validation_data=val_ds, epochs=EPOCHS,
    class_weight=class_weights, callbacks=get_callbacks("custom_cnn")
)

# ---- Model B: ResNet50 (transfer learning, frozen base) ----
resnet_model, resnet_base = build_resnet50()
resnet_model.compile(optimizer=optimizers.Adam(learning_rate=1e-4, clipnorm=1.0),
                      loss="binary_crossentropy", metrics=METRICS)
history_resnet = resnet_model.fit(
    train_ds, validation_data=val_ds, epochs=EPOCHS,
    class_weight=class_weights, callbacks=get_callbacks("resnet50")
)

# ---- (Optional) Fine-tune ResNet50: unfreeze top layers, train with a low LR ----
resnet_base.trainable = True
for layer in resnet_base.layers[:-30]:   # keep most of the network frozen
    layer.trainable = False

resnet_model.compile(optimizer=optimizers.Adam(learning_rate=1e-5),
                      loss="binary_crossentropy", metrics=METRICS)
history_resnet_ft = resnet_model.fit(
    train_ds, validation_data=val_ds, epochs=10,
    class_weight=class_weights, callbacks=get_callbacks("resnet50_finetuned")
)

# ---- Model C: CNN + Transformer hybrid ----
cnn_transformer = build_cnn_transformer()
cnn_transformer.compile(optimizer=optimizers.Adam(learning_rate=1e-4, clipnorm=1.0),
                         loss="binary_crossentropy", metrics=METRICS)
history_transformer = cnn_transformer.fit(
    train_ds, validation_data=val_ds, epochs=EPOCHS,
    class_weight=class_weights, callbacks=get_callbacks("cnn_transformer")
)

"""## 3.5 Learning Curves"""

def plot_learning_curves(history, title):
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].plot(history.history["loss"], label="train")
    axes[0].plot(history.history["val_loss"], label="val")
    axes[0].set_title(f"{title} - Loss"); axes[0].set_xlabel("Epoch"); axes[0].legend()

    axes[1].plot(history.history["accuracy"], label="train")
    axes[1].plot(history.history["val_accuracy"], label="val")
    axes[1].set_title(f"{title} - Accuracy"); axes[1].set_xlabel("Epoch"); axes[1].legend()
    plt.tight_layout()
    plt.show()

plot_learning_curves(history_cnn, "Custom CNN")
plot_learning_curves(history_resnet, "ResNet50 (frozen)")
plot_learning_curves(history_resnet_ft, "ResNet50 (fine-tuned)")
plot_learning_curves(history_transformer, "CNN + Transformer")

"""## 3.6 Evaluation on the Test Set

Metrics: Accuracy, Precision, Recall, F1-score, AUC, confusion matrix, ROC curve — for each of the three models.

"""

def evaluate_model(model, test_ds, test_df, name):
    y_true = test_df["label"].map(LABEL_MAP).values
    y_prob = model.predict(test_ds).ravel()
    y_pred = (y_prob >= 0.5).astype(int)

    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="binary")
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    roc_auc = auc(fpr, tpr)

    print(f"\n===== {name} =====")
    print(classification_report(y_true, y_pred, target_names=classes))
    print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | "
          f"F1: {f1:.4f} | AUC: {roc_auc:.4f}")

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=classes, yticklabels=classes, ax=axes[0])
    axes[0].set_title(f"{name} - Confusion Matrix")
    axes[0].set_xlabel("Predicted"); axes[0].set_ylabel("Actual")

    # ROC curve
    axes[1].plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
    axes[1].plot([0, 1], [0, 1], "--", color="gray")
    axes[1].set_title(f"{name} - ROC Curve")
    axes[1].set_xlabel("False Positive Rate"); axes[1].set_ylabel("True Positive Rate")
    axes[1].legend()
    plt.tight_layout()
    plt.show()

    return {"model": name, "accuracy": acc, "precision": prec,
            "recall": rec, "f1": f1, "auc": roc_auc}

results = []
results.append(evaluate_model(custom_cnn, test_ds, test_df, "Custom CNN"))
results.append(evaluate_model(resnet_model, test_ds, test_df, "ResNet50 (fine-tuned)"))
results.append(evaluate_model(cnn_transformer, test_ds, test_df, "CNN + Transformer"))

results_df = pd.DataFrame(results)
results_df

"""---
# PHASE 4 — Optimization and Problem Solving
*(Relevant WPs: WP1, WP2, WP3 | Weight: 20%)*

This phase demonstrates:
1. **Overfitting mitigation** — ablation study (with vs without dropout/augmentation/early stopping)
2. **Vanishing-gradient mitigation** — already built into all 3 models (BatchNorm, ReLU, residual connections, LayerNorm); we show *why* via the learning curves above and the discussion below
3. **Cross-architecture comparison** — accuracy, computational cost (params, training time), and complexity
4. Engineering interpretation: *why* certain models perform better

## 4.1 Overfitting Ablation Study

We retrain a version of the custom CNN **without** dropout, augmentation, or early stopping (i.e. a "naive" baseline), and compare its train/val gap against the regularized Model A above. A larger train-val accuracy gap = more overfitting.
"""

# 4.1  "Naive" CNN: no dropout, no augmentation, no early stopping/regularization
def build_naive_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 3)):
    inputs = layers.Input(shape=input_shape)
    x = inputs
    for filters in [32, 64, 128, 256]:
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.MaxPooling2D()(x)
    x = layers.Flatten()(x)
    x = layers.Dense(256, activation="relu")(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)
    return models.Model(inputs, outputs)

# unaugmented training set (no random flips/crops) to isolate the effect of augmentation
train_ds_noaug = make_dataset(train_df, augment=False, shuffle=True)

naive_cnn = build_naive_cnn()
naive_cnn.compile(optimizer=optimizers.Adam(learning_rate=1e-3),
                   loss="binary_crossentropy", metrics=METRICS)
history_naive = naive_cnn.fit(train_ds_noaug, validation_data=val_ds, epochs=10, verbose=1)

# 4.1b  Compare train-val accuracy gap: naive vs regularized custom CNN
def final_gap(history):
    return history.history["accuracy"][-1] - history.history["val_accuracy"][-1]

print(f"Naive CNN          - final train-val accuracy gap: {final_gap(history_naive):.4f}")
print(f"Regularized CNN (A)- final train-val accuracy gap: {final_gap(history_cnn):.4f}")

plot_learning_curves(history_naive, "Naive CNN (no dropout/augmentation)")

# >>> FILL IN AFTER RUNNING: discuss in your report how the gap differs and
# attribute the improvement to dropout + data augmentation + early stopping + BatchNorm.

"""## 4.2 Vanishing-Gradient Mitigation — Summary

| Technique | Where used | Effect |
|---|---|---|
| **Batch Normalization** | Every conv block in Models A & C | Normalizes activations, keeps gradients in a healthy range through deep stacks |
| **ReLU activation** | Models A & C | Avoids the saturating-gradient problem of sigmoid/tanh in hidden layers |
| **Residual ("skip") connections** | ResNet50 backbone (Model B) and Transformer encoder blocks (Model C) | Provides a direct gradient path to earlier layers, the core fix popularized by ResNet |
| **Layer Normalization** | Transformer encoder blocks (Model C) | Stabilizes the scale of activations entering attention/FFN sub-layers |
| **Gradient clipping (optional)** | Can be added via `optimizer=Adam(clipnorm=1.0)` | Caps gradient norm to prevent occasional exploding-gradient spikes |

## 4.3 Final Cross-Architecture Comparison
"""

# 4.3  Combine accuracy/F1/AUC results with computational complexity metrics
def count_params(model):
    return model.count_params()

complexity_df = pd.DataFrame({
    "model": ["Custom CNN", "ResNet50 (fine-tuned)", "CNN + Transformer"],
    "total_params": [count_params(custom_cnn), count_params(resnet_model), count_params(cnn_transformer)],
})

final_comparison = results_df.merge(complexity_df, on="model")

# Optional: record approximate training time per model
final_comparison["approx_train_time_sec"] = [None, None, None]

final_comparison

# 4.3b  Bar chart comparison of accuracy, F1, and AUC across models
metrics_to_plot = ["accuracy", "f1", "auc"]
final_comparison.set_index("model")[metrics_to_plot].plot(kind="bar", figsize=(9, 5))
plt.title("Model Comparison: Accuracy, F1-score, AUC")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=15)
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()